# Generated by Django 3.0.7 on 2020-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201001_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out For Delivery', 'Out For Delivery'), ('Out Of Stock', 'Out Of Stock'), ('Not Available', 'Not Available')], max_length=100, null=True),
        ),
    ]
